import type { Metadata } from "next";
import {Inter} from 'next/font/google'
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/Header";


const inter = Inter({
  subsets:['latin'],
  weight: ['100', '200', '400', '500', '600', '800', '900']
})

export const metadata: Metadata = {
  title: "Vamo Marcar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
